version: '3'

services:
    app:
        container_name: tatilbagimlisi
        build: .cloud/php
        image: app-tatilbagimlisi
        depends_on:
            - redis
        ports:
            - "9037:9000"
        volumes:
            - ./:/var/www:cached
        networks:
            - tatilbagimlisi_network

    nginx:
        container_name: tatilbagimlisi.nginx
        image: nginx
        ports:
            - "8037:8000"
        volumes:
            - .cloud/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
            - ./:/var/www:cached
        depends_on:
            - app
        networks:
            - tatilbagimlisi_network

    redis:
        container_name: tatilbagimlisi.redis
        image: redis
        ports:
            - 63737:6379
        volumes:
            - .cloud/redis/data:/data
        networks:
            - tatilbagimlisi_network

    pgres:
        container_name: tatilbagimlisi.postgres
        image: postgres
        restart: always
        ports:
            - "54337:5432"
        environment:
            POSTGRES_DB: tatilbagimlisi
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: example
            PGDATA: /tmp
        volumes:
            - .cloud/postgres/data:/var/lib/postgresql/data
        networks:
            - tatilbagimlisi_network
networks:
    tatilbagimlisi_network:
        driver: bridge
